Feature/latestupdate
dwheeler7/goose pull request #149
Opened 2024-03-22 00:48 UTC by Jcasanova1990

"created userlist/user.js/updated user routes and controllers to include  index all users/ patched app.js to include search query/ updated homepage.js to include search query/ added the scss files so that front-end can polish/ search bar finished  and added when you click on user it navigates to their profile"

2024-03-22 05:29 UTC, dwheeler7 requested changes

2024-03-22 05:29 UTC, dwheeler7 commented on src/pages/HomePage/HomePage.js
> +        navigate(`/profile/${user.id}`);
`_id` not `id`

2024-03-22 11:21 UTC, Jcasanova1990 commented on src/pages/HomePage/HomePage.js
> +        navigate(`/profile/${user.id}`);
yup just did this

2024-03-23 15:19 UTC, dwheeler7 approved these changes

2024-03-23 15:19 UTC, merged